<a href="https://colab.research.google.com/github/Josh1313/-Python_Basics-_1-/blob/main/Clase_4_NumPy_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Módulos en Python

In [1]:
import math

In [2]:
help(math)

Help on built-in module math:

NAME
    math

DESCRIPTION
    This module provides access to the mathematical functions
    defined by the C standard.

FUNCTIONS
    acos(x, /)
        Return the arc cosine (measured in radians) of x.
        
        The result is between 0 and pi.
    
    acosh(x, /)
        Return the inverse hyperbolic cosine of x.
    
    asin(x, /)
        Return the arc sine (measured in radians) of x.
        
        The result is between -pi/2 and pi/2.
    
    asinh(x, /)
        Return the inverse hyperbolic sine of x.
    
    atan(x, /)
        Return the arc tangent (measured in radians) of x.
        
        The result is between -pi/2 and pi/2.
    
    atan2(y, x, /)
        Return the arc tangent (measured in radians) of y/x.
        
        Unlike atan(y/x), the signs of both x and y are considered.
    
    atanh(x, /)
        Return the inverse hyperbolic tangent of x.
    
    ceil(x, /)
        Return the ceiling of x as an Integral.
      

In [3]:
math.e

2.718281828459045

In [4]:
#podemos asiganar la funcion a una letra

In [5]:
import math as m

In [6]:
m.log(1)

0.0

In [7]:
from math import e

In [8]:
e

2.718281828459045

In [9]:
from math import *

In [10]:
log(1)

0.0

In [11]:
#para conectar con otras meotodos no instalados" pip install pandas"

In [12]:
pip install pandas

In [13]:
#beautifulsoap para scrappe web sites

## Módulos Built-in

![title](https://static.bookstack.cn/projects/Python3_Module_Examples/module_mindmap.png)

### Math Module

In [14]:
math.radians(30)

0.5235987755982988

In [15]:
math.sin(0.5)

0.479425538604203

In [16]:
math.ceil(4.558)

5

In [17]:
math.floor(3.32)

3

In [18]:
math.floor?

###  Statistics Module

In [19]:
import statistics as st

In [20]:
st.mean([1,2,3,4])

2.5

In [21]:
st.median([1,2,3,4])

2.5

In [22]:
st.mode([1,2,3,4])

1

In [23]:
st.stdev([1,2,3,4])

1.2909944487358056

### Random module

In [24]:
import random

In [25]:
random.random()

0.08119430289704455

In [26]:
random.randint(1,100)

99

In [27]:
random.choice([1,2,3,4])

1

# Paquetes en Python

Python tiene más de 137.000 librerías disponibles, nosotros veremos algunas de las más útiles para Data Science, de las cuáles destacan las siguientes:

![title](https://cdn-images-1.medium.com/max/800/1*BeWMs7DfFaZKnNRaos72JA.png)

Librerías para tratamiento de datos:
- NumPy
- SciPy
_ Pandas
- SciKit-Learn

Mientras librerías para visualización:
- matplotlib
- Seaborn

# NumPy

![tite](https://d1jnx9ba8s6j9r.cloudfront.net/blog/wp-content/uploads/2018/11/1200px-NumPy_logo.svg_.png)

## Qué es NumPy?

NumPy (**Num**erical **Py**thon) está considerada como una de las librerías más populares de machine learning en Python, y se usa en casi todos los procesos de computación numérica de Python y librerías como Pandas, SciPy, Matplotlib, scikit-learn etc.

Algunas características de NumPy:
- Se usa para computaciones de alto rendimiento con **vectores** y **matrices**, o lo que llamamos **arrays n-dimensionales**: *ndarray()*
- Ofrece **computación vectorizada** de arrays y matrices
- Ofrece funciones y rutinas numéricas de rápida precompilación
- Está escrita en *C* y *Fortran*

## NumPy Arrays

**El array es la estructura de datos central de la librería NumPy**. Es una parrilla de valores, y contiene información de datos raw, de cómo alocar un elemento y cómo interpretarlo.

Características:

- Los elementos de la parrilla pueden ser indexados de diferentes formas.
- Los elementos tienen que ser todos de mismo tipo, que es el tipo: *array dtype*


![title](https://www.tutorialspoint.com/numpy/images/ndarray.jpg)

### Array 1d (a partir de una lista)

In [28]:
import numpy as np

In [29]:
lista = [1,2,3]

In [30]:
arr = np.array(lista)

In [31]:
arr

array([1, 2, 3])

In [32]:
arr + 1

array([2, 3, 4])

|Comando |función|
|:---|:---|
|**ndim()**|dimensión del array. 1d - creado con una lista, 2d - creado con una lista de listas|
|**shape()**|nº elementos en cada dimensión: **notación: (i,j) donde i es el nº filas y j el nº columnas**|
|**dtype()**|tipo de datos del array|
|**size()**|nº total de elementos del array|

In [33]:
arr.ndim

1

In [34]:
arr.shape

(3,)

In [35]:
arr.dtype

dtype('int64')

In [36]:
arr.size

3

![title](https://miro.medium.com/max/2600/0*Q_wCrQ29wTBHb_7Q.png)

**Las funciones aplican a nivel elemento y no a nivel objeto**

In [37]:
arr * 3

array([3, 6, 9])

In [38]:
arr / 4

array([0.25, 0.5 , 0.75])

### Array 2d (a partir de una lista de listas)

In [39]:
lista_2d = [[0,1,2], [3,4,5], [6,7,8]]

In [40]:
arr_2d = np.array(lista_2d)

In [41]:
arr_2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### Array 3d (lista de listas de listas)

In [42]:
lista_3d = [[[1,3], [2,4], [4,3]], [[3,2], [4,1], [0,3]]]

In [43]:
arr_3d = np.array(lista_3d)

In [44]:
arr_3d

array([[[1, 3],
        [2, 4],
        [4, 3]],

       [[3, 2],
        [4, 1],
        [0, 3]]])

##### Ejercicio
Genera un array que contenga las siguientes 3 listas de números.

- 1a fila: 1,2,3,4  
- 2a fila: 5,1,1,1
- 3a fila: 0,1,2,7

Determina la dimensión, el número de elementos, el tipo de datos, y el número total de elementos.

In [45]:
import numpy as np

In [46]:
import numpy as np

lista1 = [1,2,3,4]
lista2 = [5,1,1,1]
lista3 = [0,1,2,7]

array = np.array([lista1, lista2, lista3])

print(array)


[[1 2 3 4]
 [5 1 1 1]
 [0 1 2 7]]


#### np.arange(): Arrays separados de forma igual

In [47]:
import numpy as np

In [48]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [49]:
np.arange(45,65)

array([45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
       62, 63, 64])

In [50]:
np.arange(30, 10, -5)

array([30, 25, 20, 15])

#### np.linspace(): separados por nº puntos

In [51]:
np.linspace(1, 10, 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

#### np.random(): Array Aleatorio

In [52]:
np.random.rand(4)

array([0.76993516, 0.19107717, 0.59113467, 0.19343678])

In [53]:
np.random.randint(1, 10)

2

### Cambiar tipo de datos de array: astype()

In [54]:
lista_de_listas = [[0,1,2], [3,4,5], [6,7,8]]
array_2d = np.array(lista_de_listas,dtype='float')
array_2d

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

## Indexado y particionado de arrays

### Indexado de un array

In [55]:
a = np.arange(10)

In [56]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
a[0]

0

In [58]:
a[-1]

9

In [59]:
a[3:7]

array([3, 4, 5, 6])

In [60]:
a[:7]

array([0, 1, 2, 3, 4, 5, 6])

#### Indexado para multi-array

In [61]:
a = np.diag(np.arange(3))

In [62]:
a

array([[0, 0, 0],
       [0, 1, 0],
       [0, 0, 2]])

In [63]:
a[2,2]

2

In [64]:
a[:,0]

array([0, 0, 0])

In [65]:
a[:2,:2]

array([[0, 0],
       [0, 1]])

In [66]:
a[a[1]]

array([[0, 0, 0],
       [0, 1, 0],
       [0, 0, 0]])

### Slicing de un array

In [67]:
arr = np.arange (15)

In [68]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [69]:
arr[2:7:2]

array([2, 4, 6])

##### Ejercicios:
1. Generar un array que contenga las siguientes filas

1f: 1, 3, -1, 4, 5

2f: 1, 1, 2, 4, 6

3f: 6, 4, 3, 8, 2

2. Imprime la primera columna
3. Imprime la segunda fila
4. Cambia el valor del subset de las últimas 2 filas y 2 columnas a 4


In [70]:
import numpy as np

In [71]:
list_1 = [1, 3, -1, 4, 5]

list_2 = [1, 1, 2, 4, 6]

list_3 = [6, 4, 3, 8, 2]

In [72]:
list_11 = [list_1, list_2, list_3]

In [73]:
list_11

[[1, 3, -1, 4, 5], [1, 1, 2, 4, 6], [6, 4, 3, 8, 2]]

2. Escribe un programa con Numpy para crear array tipo random de 10X4 y extraer las primeras 5 filas para guardarlas en una variable.

In [74]:
np.random.rand()

0.21028318407539104

In [75]:
np.random.randint(1,100,40).reshape((10,4))

array([[ 6, 25, 21, 42],
       [ 7, 74, 77, 94],
       [71, 58, 31, 63],
       [86, 20, 55, 82],
       [17, 64, 78, 22],
       [22, 69,  8, 72],
       [69, 77,  7, 29],
       [67, 63, 35, 26],
       [80, 37, 98, 91],
       [ 8, 24, 13, 35]])

In [76]:
np.random.randint(1,100,40).reshape((10,4))[:5,:]

array([[93, 76, 54, 93],
       [29, 52, 77, 75],
       [18, 70, 74, 71],
       [13, 39, 52, 63],
       [ 8, 94, 58, 95]])

3. Crear una matriz de 10x10 con 1's en los bordes y 0's en el interior (con rangos de indices)

In [77]:
import numpy as np

# Crear una matriz de 10x10 con todos los elementos iguales a cero
matriz = np.zeros((10, 10), dtype=int)

# Asignar 1's en los bordes
matriz[0, :] = 1   # primera fila
matriz[-1, :] = 1  # última fila
matriz[:, 0] = 1   # primera columna
matriz[:, -1] = 1  # última columna

# Imprimir la matriz resultante
print(matriz)


[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [78]:
np.ones((10,10,), dtype="int")

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [79]:
np.zeros((10,10), dtype="int")

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

## Operadores sobre Arrays

#### Operadores sum(), min(), max()

In [80]:
arr = np.array(    [
                [1, 5, 6],
                [4, 7, 2],
                [3, 1, 9]
               ]   )

In [81]:
arr.sum(axis = 0)

array([ 8, 13, 17])

In [82]:
arr.min(axis = -1)

array([1, 2, 1])

In [83]:
arr.max()

9

In [84]:
arr.max(0)

array([4, 7, 9])

In [85]:
arr.max(axis = 0)

array([4, 7, 9])

#### Ejercicio
- Calcula la forma y dimensiones del array
- Calcula la suma de todos los elementos
- Remplaza el 7 por -1
- Saca el máximo a nivel de columnas y filas
- Calcula la suma de cada fila

In [86]:
arr = np.array([
    [1,5,6],
    [4,7,9],
    [3,1,9]])

In [87]:
arr

array([[1, 5, 6],
       [4, 7, 9],
       [3, 1, 9]])

In [88]:
import numpy as np

# Definimos el array
arr = np.array([[1, 5, 6], [4, 7, 9], [3, 1, 9]])

# Forma y dimensiones del array
print("Forma y dimensiones del array:", arr.shape)

# Suma de todos los elementos
print("Suma de todos los elementos:", np.sum(arr))

# Reemplazo del 7 por -1
arr[arr == 7] = -1
print("Nuevo array con 7 reemplazado por -1:\n", arr)

# Máximo a nivel de columnas y filas
print("Máximo a nivel de columnas:", np.max(arr, axis=0))
print("Máximo a nivel de filas:", np.max(arr, axis=1))

# Suma de cada fila
print("Suma de cada fila:", np.sum(arr, axis=1))


Forma y dimensiones del array: (3, 3)
Suma de todos los elementos: 45
Nuevo array con 7 reemplazado por -1:
 [[ 1  5  6]
 [ 4 -1  9]
 [ 3  1  9]]
Máximo a nivel de columnas: [4 5 9]
Máximo a nivel de filas: [6 9 9]
Suma de cada fila: [12 12 13]


In [89]:
arr.max(axis = 0)

array([4, 5, 9])

In [90]:
arr.max(1)

array([6, 9, 9])

In [91]:
arr.max(axis = 1)

array([6, 9, 9])

In [92]:
arr.sum()

37

## Métodos sobre arrays

### reshape(): Para cambiar forma de un array

In [93]:
array_1 = np.array([[1, 2, 3, 4],
                [5, 2, 4, 2],
                [1, 2, 0, 1]])

In [94]:
array_1

array([[1, 2, 3, 4],
       [5, 2, 4, 2],
       [1, 2, 0, 1]])

In [95]:
array_1.reshape((4,3))

array([[1, 2, 3],
       [4, 5, 2],
       [4, 2, 1],
       [2, 0, 1]])

In [96]:
array_1.reshape((2,6))

array([[1, 2, 3, 4, 5, 2],
       [4, 2, 1, 2, 0, 1]])

In [97]:
array_1.reshape((2,3,2))

array([[[1, 2],
        [3, 4],
        [5, 2]],

       [[4, 2],
        [1, 2],
        [0, 1]]])

### flatten(): Colapsar array en 1d

In [98]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [99]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [100]:
arr.flatten()

array([1, 2, 3, 4, 5, 6])

### T(), transpose(): Transponer un array

In [101]:
data = np.array([[1,2],[3,4],[5,6]])
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [102]:
data.T

array([[1, 3, 5],
       [2, 4, 6]])

### flip(): revertir un array a lo largo del eje

In [103]:
a = np.array([1, 2, 3, 14, 5, 6, 7, 8])

In [104]:
a

array([ 1,  2,  3, 14,  5,  6,  7,  8])

In [105]:
np.flip(a)

array([ 8,  7,  6,  5, 14,  3,  2,  1])

### unique(): para sacar elementos únicos del array


In [106]:
a = np.array([11, 11, 12, 13, 14])

In [107]:
np.unique(a)

array([11, 12, 13, 14])

### sort(): ordenar un array

In [108]:
a= np.array([[1, 4, 2],
                 [3, 4, 6],
              [0, -1, 5]])

In [109]:
np.sort(a)

array([[ 1,  2,  4],
       [ 3,  4,  6],
       [-1,  0,  5]])

In [110]:
np.sort(a, axis = 0)

array([[ 0, -1,  2],
       [ 1,  4,  5],
       [ 3,  4,  6]])

##### Ejercicio:
- Generar un array con dimensión=1  y valores del 10 al 32 con sequencia de dos en dos.
- Tranformar el array anterior a una matriz de 4 filas x 3 columnas y guardalo como arr1.
- Mostrar solo los valores de Array que sean mayores de 20
- Verificar si la media y la mediana del mismo array son iguales.
- Suma las filas y obtén el maximo valor entre las columnas.
- Genera un nuevo array arr2 con los valores mayores a 20 y que sea de 3 filas x 2 columnas.
- Genera la Transpuesta del resultado.

In [111]:
import numpy as np

# Generar un array con dimensión=1 y valores del 10 al 32 con secuencia de dos en dos.
arr = np.arange(10, 33, 2)

# Tranformar el array anterior a una matriz de 4 filas x 3 columnas y guardarlo como arr1.
arr1 = arr.reshape((4, 3))
print("Array original:\n", arr)
print("Array como matriz de 4 filas x 3 columnas:\n", arr1)

# Mostrar solo los valores de Array que sean mayores de 20.
print("Valores mayores de 20 en arr1:", arr1[arr1 > 20])

# Verificar si la media y la mediana del mismo array son iguales.
if np.mean(arr1) == np.median(arr1):
    print("La media y la mediana son iguales.")
else:
    print("La media y la mediana son diferentes.")

# Suma las filas y obtén el máximo valor entre las columnas.
suma_filas = np.sum(arr1, axis=1)
maximo_columnas = np.max(arr1, axis=0)
print("Suma de las filas de arr1:", suma_filas)
print("Máximo de las columnas de arr1:", maximo_columnas)

# Generar un nuevo array arr2 con los valores mayores a 20 y que sea de 3 filas x 2 columnas.
arr2 = arr1[arr1 > 20].reshape((3, 2))
print("Nuevo array arr2:\n", arr2)

# Generar la Transpuesta del resultado.
arr2_t = arr2.T
print("Transpuesta de arr2:\n", arr2_t)


Array original:
 [10 12 14 16 18 20 22 24 26 28 30 32]
Array como matriz de 4 filas x 3 columnas:
 [[10 12 14]
 [16 18 20]
 [22 24 26]
 [28 30 32]]
Valores mayores de 20 en arr1: [22 24 26 28 30 32]
La media y la mediana son iguales.
Suma de las filas de arr1: [36 54 72 90]
Máximo de las columnas de arr1: [28 30 32]
Nuevo array arr2:
 [[22 24]
 [26 28]
 [30 32]]
Transpuesta de arr2:
 [[22 26 30]
 [24 28 32]]
